spring:
  application:
    name: passenger
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        prefix: ${spring.application.name}
        file-extension: yml
      discovery:
        server-addr: 127.0.0.1:8848
# dataId默认格式 ${prefix}-${spring.profiles.active}.${file-extension}
# prefix 为 spring.application.name
# file-extension 为文件后缀
# 使用命令发布配置  curl -X POST "http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=passenger-dev.yml&group=DEFAULT_GROUP&content=xxxxx配置文件内容"
server:
  port: 8091
  